#!/bin/bash

TAILLE=`cat Test.log | wc -c`

if [ $TAILLE -gt 0 ]
#then cat Test.log | mail -s "Test AVC, ALERTE ALERTE ALERTE" eric.laemmer@ulpmm.u-strasbg.fr morgan.bohn@ulpmm.u-strasbg.fr
then /etc/init.d/tomcat5.5 restart
/etc/init.d/apache2 restart
date >> script.log
fi
