#!/bin/bash

#gunzip *.gz
fgrep /var/log/apache2/access-univ-rav.log -e .xml >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/xml.log
fgrep /var/log/apache2/access-univ-rav.log -e .mp3 >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp3.log
fgrep /var/log/apache2/access-univ-rav.log -e .ogg >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/ogg.log
fgrep /var/log/apache2/access-univ-rav.log -e .pdf >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/pdf.log
fgrep /var/log/apache2/access-univ-rav.log -e .smil >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/smil.log
fgrep /var/log/apache2/access-univ-rav.log -e .zip >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/zip.log
fgrep /var/log/apache2/access-univ-rav.log -e .flv >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/flv.log
fgrep /var/log/apache2/access-univ-rav.log -e .rm >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/rm.log
fgrep /var/log/apache2/access-univ-rav.log -e .mp4 >> /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp4.log

visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/xml.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/xml.html
visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp3.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp3.html
visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/ogg.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/ogg.html
visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/pdf.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/pdf.html
visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/smil.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/smil.html
visitors -B -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/zip.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/zip.html
visitors -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/flv.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/flv.html
visitors -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/rm.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/rm.html
visitors -p 2000 /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp4.log > /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/mp4.html

mv /var/lib/tomcat5.5/webapps/univ-r_av/scripts/AVC_Stat_scpt/*.html /var/www/webalizer/avc/
